_target_: diffusion_policy.workspace.train_diffusion_unet_hybrid_workspace.TrainDiffusionUnetHybridWorkspace
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 3
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 16
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: 2024.05.14_train_diffusion_unet_hybrid_vis_image
  project: vis_diffusion_policy
  resume: true
  tags:
  - train_diffusion_unet_hybrid
  - vis_image
  - default
multi_run:
  run_dir: ../Data/TrainModels/2024.05.14/14.50.00_train_diffusion_unet_hybrid_vis_image
  wandb_name_base: 2024.05.14_train_diffusion_unet_hybrid_vis_image
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
name: train_diffusion_unet_hybrid
obs_as_global_cond: true
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.diffusion_unet_hybrid_image_policy.DiffusionUnetHybridImagePolicy
  cond_predict_scale: true
  crop_shape:
  - 280
  - 140
  diffusion_step_embed_dim: 512
  down_dims:
  - 512
  - 1024
  - 2048
  eval_fixed_crop: true
  horizon: 16
  kernel_size: 5
  n_action_steps: 8
  n_groups: 8
  n_obs_steps: 2
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 100
    prediction_type: epsilon
    variance_type: fixed_small
  num_inference_steps: 100
  obs_as_global_cond: true
  obs_encoder_group_norm: true
  shape_meta:
    action:
      shape:
      - 2
    obs:
      image1:
        shape:
        - 3
        - 400
        - 200
        type: rgb
      image2:
        shape:
        - 3
        - 400
        - 200
        type: rgb
shape_meta:
  action:
    shape:
    - 2
  obs:
    image1:
      shape:
      - 3
      - 300
      - 150
      type: rgb
    image2:
      shape:
      - 3
      - 300
      - 150
      type: rgb
task:
  dataset:
    _target_: diffusion_policy.dataset.vis_image_dataset.VISImageDataset
    horizon: 16
    max_train_episodes: null
    pad_after: 7
    pad_before: 1
    seed: 42
    val_ratio: 0.1
    zarr_path: ../Data/TrainData/vis_demo.zarr
  env_runner:
    _target_: diffusion_policy.env_runner.vis_image_runner.VISImageRunner
    fps: 10
    max_steps: 200
    n_action_steps: 8
    n_envs: null
    n_obs_steps: 8
    n_test: 50
    n_test_vis: 4
    n_train: 6
    n_train_vis: 2
    past_action: false
    test_start_seed: 1000
    train_start_seed: 0
  image_shape:
  - 3
  - 300
  - 150
  name: vis_image
  shape_meta:
    action:
      shape:
      - 2
    obs:
      image1:
        shape:
        - 3
        - 300
        - 150
        type: rgb
      image2:
        shape:
        - 3
        - 300
        - 150
        type: rgb
task_name: vis_image
training:
  checkpoint_every: 10
  debug: true
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 1000
  resume: true
  rollout_every: 10
  sample_every: 2
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
val_dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false
