_target_: diffusion_policy.workspace.train_diffusion_transformer_hybrid_workspace.TrainDiffusionTransformerHybridWorkspace
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 3
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 32
  num_workers: 4
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 8
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 16
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: ${now:%Y.%m.%d_%H.%M.%S}_train_diffusion_transformer_hybrid_branches_image
  project: branches_diffusion_policy
  resume: true
  tags:
  - train_diffusion_transformer_hybrid
  - vis_image
  - default
multi_run:
  run_dir: ../Data/TrainModels/2024.05.14/14.50.00_train_diffusion_transformer_hybrid_vis_image
  wandb_name_base: 2024.05.14_train_diffusion_transformer_hybrid_vis_image
n_action_steps: 4
n_latency_steps: 4
n_obs_steps: 8
name: train_diffusion_transformer_hybrid
obs_as_cond: true
optimizer:
  betas:
  - 0.9
  - 0.95
  learning_rate: 0.0001
  obs_encoder_weight_decay: 1.0e-06
  transformer_weight_decay: 0.001
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.diffusion_transformer_hybrid_image_policy.DiffusionTransformerHybridImagePolicy
  causal_attn: true
  crop_shape:
  - 280
  - 280
  eval_fixed_crop: true
  horizon: 16
  n_action_steps: 4
  n_cond_layers: 0
  n_emb: 256
  n_head: 4
  n_layer: 8
  n_obs_steps: 8
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    beta_start: 0.0001
    clip_sample: true
    num_train_timesteps: 100
    prediction_type: epsilon
    variance_type: fixed_small
  num_inference_steps: 100
  obs_as_cond: true
  obs_encoder_group_norm: true
  shape_meta:
    action:
      shape:
      - 2
    obs:
      image:
        shape:
        - 3
        - 300
        - 300
        type: rgb
      # controllerState:
      #   shape:
      #   - 2
      #   type: low_dim
shape_meta:
  action:
    shape:
    - 2
  obs:
    image:
      shape:
      - 3
      - 300
      - 300
      type: rgb
    # controllerState:
    #   shape:
    #   - 2
    #   type: low_dim
task:
  dataset:
    _target_: diffusion_policy.dataset.branches_image_dataset.branchesImageDataset
    horizon: 16
    pad_after: 0
    pad_before: 0
    seed: 42
    val_ratio: 0.1
    zarr_path: ../Data/TrainData/branches_demo3.zarr
  env_runner:
    _target_: diffusion_policy.env_runner.branches_image_runner.branchesImageRunner
    fps: 10
    max_steps: 300
    n_action_steps: 4
    n_envs: null
    n_obs_steps: 8
    n_test: 8
    n_test_vis: 4
    n_train: 12
    n_train_vis: 6
    past_action: false
    test_start_seed: 1000
    train_start_seed: 0
  image_shape:
  - 3
  - 300
  - 300
  name: vis_image
  shape_meta:
    action:
      shape:
      - 2
    obs:
      image:
        shape:
        - 3
        - 300
        - 300
        type: rgb
      # controllerState:
      #   shape:
      #   - 2
      #   type: low_dim
task_name: branches_image
training:
  checkpoint_every: 10
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 1000
  resume: true
  rollout_every: 10
  sample_every: 1
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 2
val_dataloader:
  batch_size: 16
  num_workers: 2
  persistent_workers: false
  pin_memory: true
  shuffle: false
